version: "3.1"
services:
    drupal_web:
        image: drupal
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        ports:
            - 80:80
        depends_on:
            - postgres_db
        deploy:
            replicas: 2
    postgres_db:
        image: postgres
        volumes:
            - psql-data:/var/lib/postgresql/data
        secrets:
            - psql_user
            - psql_password
        environment:
            POSTGRES_USER_FILE: /run/secrets/psql_user
            POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
        
volumes:
    - drupal-modules
    - drupal-profiles
    - drupal-sites
    - drupal-themes
    - psql_data
secrets:
    psql_user:
        file: ./psql_user.txt
    psql_password:
        external: true