version: "3.0"
services:
    nginx:
        image: nginx:1.18
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    web:
        image: httpd
